# Generated by Django 4.2.23 on 2025-08-15 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_monthly_analyses_used_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email_property_alerts',
            field=models.BooleanField(default=True, help_text='Receive emails about new properties that are good deals'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='max_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum price for properties to include in alerts', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='min_investment_score',
            field=models.IntegerField(default=70, help_text='Minimum investment score for properties to include in alerts'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='preferred_locations',
            field=models.JSONField(blank=True, default=list, help_text="List of preferred locations for property alerts (e.g., ['Tirana', 'Durrës'])"),
        ),
    ]
