# Generated by Django 4.2.23 on 2025-08-10 08:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyAnalysis',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('property_url', models.URLField()),
                ('property_title', models.CharField(max_length=500)),
                ('property_location', models.CharField(max_length=255)),
                ('asking_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('property_type', models.CharField(blank=True, max_length=50)),
                ('bedrooms', models.IntegerField(blank=True, null=True)),
                ('bathrooms', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('square_meters', models.IntegerField(blank=True, null=True)),
                ('analysis_result', models.JSONField(default=dict)),
                ('ai_summary', models.TextField(blank=True)),
                ('investment_score', models.IntegerField(blank=True, null=True)),
                ('recommendation', models.CharField(blank=True, choices=[('strong_buy', 'Strong Buy'), ('buy', 'Buy'), ('hold', 'Hold'), ('avoid', 'Avoid')], max_length=20, null=True)),
                ('status', models.CharField(choices=[('analyzing', 'Analyzing'), ('completed', 'Completed'), ('failed', 'Failed')], default='analyzing', max_length=20)),
                ('report_generated', models.BooleanField(default=False)),
                ('report_file_path', models.CharField(blank=True, max_length=500)),
                ('processing_stage', models.CharField(blank=True, max_length=50, null=True)),
                ('processing_started_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
