# Generated by Django 4.2.23 on 2025-08-10 12:13

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('property_ai', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propertyanalysis',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='propertyanalysis',
            old_name='square_meters',
            new_name='internal_area',
        ),
        migrations.RemoveField(
            model_name='propertyanalysis',
            name='processing_started_at',
        ),
        migrations.AddField(
            model_name='propertyanalysis',
            name='ceiling_height',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='propertyanalysis',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='propertyanalysis',
            name='facade_length',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='propertyanalysis',
            name='floor_level',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='propertyanalysis',
            name='furnished',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propertyanalysis',
            name='has_elevator',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propertyanalysis',
            name='listing_code',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='propertyanalysis',
            name='property_condition',
            field=models.CharField(blank=True, choices=[('new', 'New'), ('used', 'Used'), ('renovation_needed', 'Needs Renovation')], max_length=20),
        ),
        migrations.AddField(
            model_name='propertyanalysis',
            name='property_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='propertyanalysis',
            name='total_area',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propertyanalysis',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='propertyanalysis',
            name='investment_score',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='propertyanalysis',
            name='property_type',
            field=models.CharField(blank=True, choices=[('apartment', 'Apartment'), ('villa', 'Villa'), ('commercial', 'Commercial'), ('office', 'Office'), ('studio', 'Studio'), ('land', 'Land'), ('business', 'Business')], max_length=50),
        ),
        migrations.AlterField(
            model_name='propertyanalysis',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='property_analyses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='propertyanalysis',
            index=models.Index(fields=['property_location', 'property_type'], name='property_ai_propert_700947_idx'),
        ),
        migrations.AddIndex(
            model_name='propertyanalysis',
            index=models.Index(fields=['asking_price'], name='property_ai_asking__41aca6_idx'),
        ),
        migrations.AddIndex(
            model_name='propertyanalysis',
            index=models.Index(fields=['investment_score'], name='property_ai_investm_14f4f0_idx'),
        ),
        migrations.AddIndex(
            model_name='propertyanalysis',
            index=models.Index(fields=['status'], name='property_ai_status_ceadbb_idx'),
        ),
    ]
