# Generated by Django 4.2.23 on 2025-08-10 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_ai', '0002_alter_propertyanalysis_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyanalysis',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Property still available online'),
        ),
        migrations.AddField(
            model_name='propertyanalysis',
            name='last_checked',
            field=models.DateTimeField(blank=True, help_text='Last time URL was verified', null=True),
        ),
        migrations.AddField(
            model_name='propertyanalysis',
            name='removed_date',
            field=models.DateTimeField(blank=True, help_text='When property was no longer accessible', null=True),
        ),
    ]
