# Generated by Django 4.2.23 on 2025-08-10 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_ai', '0003_propertyanalysis_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyanalysis',
            name='neighborhood',
            field=models.CharField(blank=True, help_text='Neighborhood/District', max_length=100),
        ),
    ]
