# Generated by Django 4.2.23 on 2025-08-10 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_ai', '0004_propertyanalysis_neighborhood'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyanalysis',
            name='neighborhood',
            field=models.CharField(blank=True, help_text='Neighborhood/District', max_length=100, null=True),
        ),
    ]
