# Generated by Django 4.2.23 on 2025-08-12 16:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('property_ai', '0005_alter_propertyanalysis_neighborhood'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyanalysis',
            name='scraped_by',
            field=models.ForeignKey(blank=True, help_text='User who initiated the scrape', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scraped_properties', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='propertyanalysis',
            name='property_url',
            field=models.URLField(unique=True),
        ),
        migrations.AlterField(
            model_name='propertyanalysis',
            name='user',
            field=models.ForeignKey(blank=True, help_text='User who requested this analysis', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='property_analyses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='propertyanalysis',
            index=models.Index(fields=['property_url'], name='property_ai_propert_afe176_idx'),
        ),
        migrations.AddIndex(
            model_name='propertyanalysis',
            index=models.Index(fields=['scraped_by'], name='property_ai_scraped_32ae07_idx'),
        ),
    ]
