# Generated by Django 4.2.23 on 2025-08-13 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_ai', '0006_propertyanalysis_scraped_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyanalysis',
            name='agent_email',
            field=models.EmailField(blank=True, help_text='Agent email contact', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='propertyanalysis',
            name='agent_name',
            field=models.CharField(blank=True, help_text='Agent handling this property', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='propertyanalysis',
            name='agent_phone',
            field=models.CharField(blank=True, help_text='Agent phone number', max_length=20, null=True),
        ),
        migrations.AddIndex(
            model_name='propertyanalysis',
            index=models.Index(fields=['agent_name'], name='property_ai_agent_n_c23897_idx'),
        ),
    ]
