# Generated by Django 4.2.23 on 2025-08-13 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_ai', '0007_propertyanalysis_agent_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapingProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_scraped_page', models.IntegerField(default=0)),
                ('total_properties_found', models.IntegerField(default=0)),
                ('bootstrap_complete', models.BooleanField(default=False)),
                ('last_update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Scraping Progress',
            },
        ),
    ]
