# Generated by Django 4.2.23 on 2025-08-13 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_ai', '0008_scrapingprogress'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComingSoonSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Coming Soon Subscription',
                'verbose_name_plural': 'Coming Soon Subscriptions',
                'ordering': ['-subscribed_at'],
            },
        ),
    ]
