# Generated by Django 4.2.23 on 2025-08-13 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property_ai', '0009_comingsoonsubscription'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ScrapingProgress',
        ),
    ]
