# Generated by Django 4.2.23 on 2025-08-15 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_ai', '0010_delete_scrapingprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyanalysis',
            name='market_opportunity_score',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Market opportunity score (0-100)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='propertyanalysis',
            name='market_position_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price position vs market average (%)', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='propertyanalysis',
            name='market_sentiment',
            field=models.CharField(blank=True, choices=[('bullish', 'Bullish'), ('neutral', 'Neutral'), ('bearish', 'Bearish')], help_text='Market sentiment at analysis time', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='propertyanalysis',
            name='negotiation_leverage',
            field=models.CharField(blank=True, choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], help_text="Buyer's negotiation leverage", max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='propertyanalysis',
            name='price_percentile',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Price percentile among comparable properties', max_digits=5, null=True),
        ),
    ]
