# Generated by Django 5.2 on 2025-04-03 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site_name', models.CharField(default='My Site', max_length=255)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('max_free_usages', models.IntegerField(default=3)),
                ('premium_price', models.DecimalField(decimal_places=2, default=5.99, max_digits=6)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
